import { Gift, Building2, Users, Sparkles } from "lucide-react";

const features = [
  {
    icon: Building2,
    title: "AI-Powered Listings",
    description: "Guesthouses get professionally crafted, employer-friendly listings generated by AI to maximize appeal.",
  },
  {
    icon: Gift,
    title: "Digital Gift Cards",
    description: "Transform bulk stays into beautiful, personalized digital gift cards your employees will love.",
  },
  {
    icon: Users,
    title: "Flexible Redemption",
    description: "Employees redeem individually at different times, fitting their schedules perfectly.",
  },
  {
    icon: Sparkles,
    title: "Off-Peak Value",
    description: "Access exclusive rates during off-season periods, maximizing your reward budget impact.",
  },
];

const Features = () => {
  return (
    <section className="py-24 px-4 bg-background relative overflow-hidden">
      {/* Subtle pattern */}
      <div className="absolute inset-0 opacity-[0.02]" style={{
        backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
      }} />
      
      <div className="container mx-auto max-w-6xl relative z-10">
        <div className="text-center mb-16 animate-fade-in">
          <span className="inline-block px-4 py-1.5 mb-4 text-sm font-medium text-primary bg-primary/10 rounded-full">
            Why Unwind
          </span>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">
            A smarter way to reward
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Bridge the gap between corporate rewards and island getaways with our 
            AI-powered platform designed for modern businesses.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <div
              key={feature.title}
              className="group p-6 rounded-2xl bg-card border border-border/50 shadow-card hover:shadow-medium transition-all duration-300 hover:-translate-y-1"
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <div className="w-12 h-12 rounded-xl gradient-ocean flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300">
                <feature.icon className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-muted-foreground text-sm leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
